<a href="https://colab.research.google.com/github/Binarybug-debug/Dynamics-/blob/main/Group_Work_Data_Visualization_and_Understanding_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here we will make inference of the Life Expectancy Data to understand Data Visualization and Measures of Central Tendency as taught by Mr. Noah Kandie

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Reading the Data
df = pd.read_csv('Life Expectancy Data.csv')

In [3]:
# 1. Data Understanding // 2D shape (rows, columns) [0,1] // 3D array (layer,row,columns)[0,1,2]
print(f"Number of observations (rows): {df.shape[0]}")
print(f"Number of variables (columns): {df.shape[1]}")

Number of observations (rows): 2938
Number of variables (columns): 22

In [8]:
df.shape

(2938, 22)

In [9]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [16]:
#df.fillna(df.mean()).mean()*100 #this replacesReplace NaNs with column means
(df.isna().mean()*100).sort_values(ascending=False)

Population                         22.191967
Hepatitis B                        18.822328
GDP                                15.248468
Total expenditure                   7.692308
Alcohol                             6.603131
Income composition of resources     5.684139
Schooling                           5.547992
 thinness  1-19 years               1.157250
 thinness 5-9 years                 1.157250
 BMI                                1.157250
Diphtheria                          0.646698
Polio                               0.646698
Life expectancy                     0.340368
Adult Mortality                     0.340368
infant deaths                       0.000000
Status                              0.000000
Country                             0.000000
Year                                0.000000
under-five deaths                   0.000000
Measles                             0.000000
percentage expenditure              0.000000
 HIV/AIDS                           0.000000
dtype: float64

In [19]:
#2. Categorical and Numerical
numerical_variable = df.select_dtypes(include = ['number']).columns.tolist()
print(f"Numerical Variables: {numerical_variable}")

categorical_variable = df.select_dtypes(exclude = ['number']).columns.tolist()
print(f"Categorical Variable: {categorical_variable}")

Numerical Variables: ['Year', 'Life expectancy ', 'Adult Mortality', 'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B', 'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population', ' thinness  1-19 years', ' thinness 5-9 years', 'Income composition of resources', 'Schooling']
Categorical Variable: ['Country', 'Status']

In [5]:
# 3. Cleaned Data
df_cleaned = df.dropna()

print(f"Cleaned dataset: {df_cleaned.info()}")
print(f"Original dataset: {df.info()}")

<class 'pandas.core.frame.DataFrame'>
Index: 1649 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          1649 non-null   object
 1   Year                             1649 non-null   int64
 2   Status                           1649 non-null   object
 3   Life expectancy                  1649 non-null   float64
 4   Adult Mortality                  1649 non-null   float64
 5   infant deaths                    1649 non-null   int64
 6   Alcohol                          1649 non-null   float64
 7   percentage expenditure           1649 non-null   float64
 8   Hepatitis B                      1649 non-null   float64
 9   Measles                          1649 non-null   int64
 10   BMI                             1649 non-null   float64
 11  under-five deaths                1649 non-null   int64
 12  Polio                            1649 non-null   float64
 13  Total expenditure                1649 non-null   float64
 14  Diphtheria                       1649 non-null   float64
 15   HIV/AIDS                        1649 non-null   float64
 16  GDP                              1649 non-null   float64
 17  Population                       1649 non-null   float64
 18   thinness  1-19 years            1649 non-null   float64
 19   thinness 5-9 years              1649 non-null   float64
 20  Income composition of resources  1649 non-null   float64
 21  Schooling                        1649 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 296.3+ KB
Cleaned dataset: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB
Original dataset: None

In [6]:
# 4. Central Tendancies
polio_deaths = df_cleaned['Polio']

mean_polio = np.mean(polio_deaths)
median_polio = np.median(polio_deaths)
max_polio = max(polio_deaths)
min_polio = min(polio_deaths)
std_polio = np.std(polio_deaths)
mode_polio = polio_deaths.mode()[0]

range_polio = max_polio - min_polio

print(f"Polio - Mean: {mean_polio}")
print(f"Polio - Median: {median_polio}")
print(f"Polio - Mode: {mode_polio}")
print(f"Polio - Standard Deviation: {std_polio}")
print(f"Polio - Min: {min_polio}")
print(f"Polio - Max: {max_polio}")
print(f"Polio - Range: {range_polio}")

Polio - Mean: 83.56458459672528
Polio - Median: 93.0
Polio - Mode: 99.0
Polio - Standard Deviation: 22.443749127951126
Polio - Min: 3.0
Polio - Max: 99.0
Polio - Range: 96.0

In [7]:
# Shape interpretation
if mean_polio > median_polio:
    print("The distribution is likely right-skewed.")
elif mean_polio < median_polio:
    print("The distribution is likely left-skewed.")
else:
    print("The distribution is likely symmetric.")

status_mode = df_cleaned['Country'].mode()[0]
print(f"Most common country: {status_mode}")

The distribution is likely left-skewed.
Most common country: Afghanistan